sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - docker build -t cwilko/mqtt-chromecast-server .


script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push cwilko/mqtt-chromecast-server
  - docker push cwilko/mqtt-chromecast-server:arm32v7