apiVersion: v1
data:
  server.ini: |+
    [MQTT]
    host = 192.168.1.202
    port = 1883
    topic = home/chromecast

    [CHROMECAST]
    device = Kitchen display
    #device = SHIELD

kind: ConfigMap
metadata:
  creationTimestamp: "2020-02-20T21:40:47Z"
  name: mqtt-chromecast-config
  namespace: actions
  resourceVersion: "8055979"
  selfLink: /api/v1/namespaces/default/configmaps/mqtt-chromecast-config
  uid: 189926a6-4040-4103-94b6-45af790f0a5c
